modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power"
version="2.6.2"
displayName="Keepers of the Stones"
credits="Created by MagicalAlexey, with the support of Chiffon Medal, FixEnd, 7ZLBeka, Superlexaan as well as many other contributors."
displayURL="https://www.curseforge.com/minecraft/mc-mods/keepers-of-the-stones"
updateJSONURL="https://raw.githubusercontent.com/MagicalAlexey/Keepers-of-the-Stones/main/kos.json"
logoFile="logo.png"
authors="Hexagon Studio"
description='''
This mod will add new sources of energy to the world with which you can transform into masters of the elements.
'''

[[dependencies.power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.power]]
    modId="pehkui"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

